[package]

name = "conduit-json-parser"
version = "0.5.4"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
description = "Middleware to parse incoming JSON requests for conduit"
repository = "https://github.com/conduit-rust/conduit-json-parser"
license = "MIT"

[dependencies]
conduit = "0.5.0"
conduit-middleware = "0.5.0"
conduit-utils = "0.5.0"
semver = "0.1.0"
rustc-serialize = "0.2"

[dev-dependencies]
conduit-test = "0.5.0"
